services:
  web:
    build:
      context: .
      args:
        BUILD_CONFIGURAION: Development
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
  redis:
    image: "redis:alpine"