services:
  web:
    build:
      context: .
      args:
        BUILD_CONFIGURATION: Development
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - "//x/Music:/var/music"
  #redis:
    #image: "redis:alpine"