services:
  web:
    build:
      context: .
      args:
        BUILD_CONFIG: Development
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  redis:
    image: "redis:alpine"