// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MediaLibrary.DAL.Models
{
    [Table("Episode")]
    public partial class Episode
    {
        public Episode()
        {
            PlaylistEpisodes = new HashSet<PlaylistEpisode>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(256)]
        public string Title { get; set; }
        public int SeriesId { get; set; }
        public int? Season { get; set; }
        [Required]
        [StringLength(256)]
        public string Path { get; set; }
        public int PlayCount { get; set; }
        public int Progress { get; set; }
        public DateTime? LastPlayedDate { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime ModifyDate { get; set; }

        [ForeignKey(nameof(SeriesId))]
        [InverseProperty("Episodes")]
        public virtual Series Series { get; set; }
        [InverseProperty(nameof(PlaylistEpisode.Episode))]
        public virtual ICollection<PlaylistEpisode> PlaylistEpisodes { get; set; }
    }
}