// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MediaLibrary.DAL.Models
{
    public partial class Series
    {
        public Series()
        {
            Episodes = new HashSet<Episode>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(256)]
        public string Title { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime ModifyDate { get; set; }

        [InverseProperty(nameof(Episode.Series))]
        public virtual ICollection<Episode> Episodes { get; set; }
    }
}